on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GOLANG_CI_LINT_VERSION: v1.50.0
  GOPRIVATE: "github.com/cloudy-sky-software/*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - run: |
          git config --global url."https://praneetloke:${GH_REPO_PAT}@github.com/".insteadOf "https://github.com/"
        env:
          GH_REPO_PAT: ${{ secrets.GH_REPO_PAT }}

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANG_CI_LINT_VERSION
          make lint

      - name: Test
        run: make test

