on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.24.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: f08454af877ea2a5246a58683951857b61853eab
          install-mode: goinstall

      - name: Lint
        run: make lint

      - name: Test
        run: make test
