on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.24.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Use a commit hash from https://github.com/golangci/golangci-lint/commits/main.
          version: 96b640c21965f1ddcc2c4c55937a0cf8dcd82fb4
          install-mode: goinstall
          args: --config=.golangci.yaml --timeout=10m

      - name: Test
        run: make test
