on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.26.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@f8208ee75bbfe589bb30d9a5f8646f8df0f1bca3
        with:
          # Use a commit hash from https://github.com/golangci/golangci-lint/commits/main.
          version: 8920f7a763476de3e0dc3d8e548641f1607aba91
          install-mode: goinstall
          args: --config=.golangci.yaml --timeout=10m

      - name: Test
        run: make test
